#!/usr/bin/env bash

set -u

echo " Univalent GNU/Linux"
echo " Version Rolling"
echo " (C) Radio New Japan Broadcasting Club"
echo ""
echo " Univalent wouldn't have been possible without the Arch Linux"
echo " Project and its many contributors." 
echo ""
echo " This product is licensed under terms of"
echo " GNU General Public License, Version 3.0 to:"
echo "  $(whoami)"
