#!/bin/sh
if [ "$(whoami)" != "root" ];then
  echo "Need to be root or run with sudo. Exiting."
  exit 1
fi

pacman -Syu
pacman -S wine wine-mono wine-gecko wine-desktop-entries lib32-alsa-lib lib32-alsa-plugins lib32-libpulse lib32-alsa-oss lib32-openal lib32-libxml2 lib32-mpg123 lib32-lcms2 lib32-giflib lib32-libpng lib32-gnutls gst-plugins-base gst-plugins-good gst-plugins-bad gst-plugins-ugly lib32-gst-plugins-base lib32-gst-plugins-good